# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edb0295070aa1f3334a2a913aa74027fe67a22753487bf313e6a87f98019a7f146c95f26b7fe2910930deb473764205b6a8ac4d9fc57a32138a1bc5cd3c61937

test:
  secret_key_base: d4fd1b22c2b0b968f37098b18a1a736dfccc3baaa52e279341526a4f10fac04ec99f166472fed20430da45b9dc513ef9660f093e6daf50b96d2c0b6d50185f23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
